// src/components/RepoCard.svelte
<script>
  import { Code, ExternalLink, Scale, Star } from './Icons/index.ts'

  export let repository
</script>

<div
  class='flex flex-col justify-between bg-white rounded-lg shadow hover:shadow-xl divide-y overflow-hidden transform ease-out duration-200 hover:-translate-y-1'
>
  <!-- Repo Description -->
  <a
    href={repository.html_url}
    class='relative block p-4 sm:p-6 group'
    target='_blank'
    rel='noopener'
  >
    <div class='flex flex-col space-y-2'>
      <img
        class='w-14 h-14 rounded-full'
        src={repository.owner.avatar_url}
        alt="Author's Avatar"
      />

      <h2 class='text-gray-900 text-xl overflow-hidden overflow-ellipsis'>
        {repository.name}
      </h2>

      {#if repository.description}
        <p class='text-gray-700 group-hover:text-gray-900 line-clamp-3 transition-colors ease-out duration-200'>
          {repository.description}
        </p>
      {/if}
    </div>

    <div class='fixed right-0 top-0 p-4'>
      <ExternalLink
        class='opacity-0 group-hover:opacity-100 w-6 h-6 text-gray-500 transition-opacity ease-out duration-200' />
    </div>
  </a>

  <!-- Repo Metadata -->
  <div class='grid grid-cols-3 bg-gray-100 text-gray-500 text-xs sm:text-sm font-semibold divide-x'>
    <!-- Language -->
    <div class='flex items-center justify-center hover:bg-gray-200 hover:text-gray-900 p-4 sm:p-6 space-x-1 group'>
      <Code class='flex-shrink-0 w-4 sm:w-5 h-4 sm:h-5 group-hover:text-blue-500' />

      <span class:italic={!repository.language}>
        {repository.language ?? 'N/A'}
      </span>
    </div>

    <!-- Stars -->
    <a
      class='flex items-center justify-center hover:bg-gray-200 hover:text-gray-900 p-4 sm:p-6 space-x-1 group'
      href='{repository.html_url}/stargazers'
      target='_blank'
      rel='noopener'
    >
      <Star class='flex-shrink-0 w-4 sm:w-5 h-4 sm:h-5 group-hover:text-amber-600' />

      <span>
        {repository.stargazers_count}
      </span>
    </a>

    <!-- License -->
    <div class='flex items-center justify-center hover:bg-gray-200 hover:text-gray-900 p-4 sm:p-6 space-x-1 group'>
      <Scale class='flex-shrink-0 w-4 sm:w-5 h-4 sm:h-5' />

      <span
        class:italic={!repository.license}
        class:group-hover:text-gray-500={!repository.license}
      >
        {repository.license?.spdx_id ?? 'N/A'}
      </span>
    </div>
  </div>
</div>

// src/components/RepoCard.vue
<template>
    <div class="gitcards gc-repo-wrap">
        <div class="gc-repo">
            <img class="gc-icon" :src="data['owner']['avatar_url']"  :alt="data['owner']['login'] + ' Avatar'"/>
            <a :href="data['html_url']" target="_blank">
                <span class="gc-reponame">{{ data['full_name'] }}</span>
                <span class="gc-respodesc">{{ data['description'] }}</span>
            </a>
        </div>
        <div class="gc-status">
            <a :href="data['html_url']" target="_blank">
                <v-icon small>fas fa-code</v-icon>

                <span v-if="data['language']">
                    {{ data['language'] }}
                </span>
                <span v-else><i>N/A</i></span>
            </a>
            <a :href="data['html_url'] + '/stargazers'" target="_blank">
                <v-icon small>fas fa-star</v-icon>

                <span>
                    {{ data['stargazers_count'] }}
                </span>
            </a>
            <a :href="data['html_url']" target="_blank">
                <v-icon small>fas fa-balance-scale</v-icon>

                <span v-if="data['license']">
                    {{ data['license']['spdx_id'] }}
                </span>
                <span v-else><i>N/A</i></span>
            </a>
        </div>
    </div>
</template>

<script>
    export default {
        name: "RepoCard",
        props: {
            data: Object
        }
    }
</script>

<style lang="scss" scoped>
    .gitcards {
        margin: 10px;
        padding: 10px;
        //width: 270px;
        height: 150px;
        border: 1px solid #d8d8d8;
        border-radius: 3px;
        font: 14px/1.5 Helvetica,arial,sans-serif;
        color: #333;
        overflow: hidden;
        box-sizing: border-box;

        p {
            margin: 0;
            padding: 0;
        }

        p, ul li, .gc-repo span {
            //width: 158px;
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
        }

        .gc-repo-wrap {
            height:98px;
        }

        .gc-icon {
            display: inline-block;
            width: 12px;
            height: 12px;
            margin-right: 6px;
            fill: #666;
        }

        a {
            text-decoration: none;
            color: #333;
            border: none;

            &:hover {
                color: #2879d0;
            }
        }

        .gc-user {
            position: relative;
            padding-left: 90px;

            a:hover {
                border-bottom:1px dashed #666;
            }
        }

        img {
            position: absolute;
            left: 0;
            top: 0;
            width: 76px;
            height: 76px;
            border-radius: 38px;
        }

        .gc-nickname {
            font-size:16px;
        }

        .gc-login {
            font-size: 12px;
            color: #666;
            padding-left: 6px;
        }

        ul {
            list-style: none;
            margin: 0;
            padding:0;

            li {
                height:20px;
                font-size:14px;
                line-height:18px;
            }
        }

        .gc-status {
            margin-top: 4px;
            padding-top: 4px;
            border-top: 1px solid #f2f2f2;

            a {
                display: inline-block;
                width: 30%;
                text-align: center;
                font-size: 12px;

                &:last-child {
                    width:40%;
                }
            }

            strong {
                display: block;
                font-size: 14px;
            }
        }

        .gc-repo {
            position: relative;
            padding-left: 40px;

            .gc-icon {
                position: absolute;
                left: 0;
                top: 6px;
                width: 32px;
                height: 32px;
            }

            span {
                display: block;
                //width: 208px;
            }
        }

        .gc-reponame {
            font-size: 18px;
        }

        .nodesc {
            .gc-reponame {
                font-size: 18px;
                height: 46px;
                line-height: 46px;
            }
        }

        .gc-repodesc {
            font-size: 13px;
            color: #666;
        }

        .gc-loading {
            position: relative;
            height: 100%;
            width: 100%;

            svg {
                position: absolute;
                left: 50%;
                top: 50%;
                width: 32px;
                height: 32px;
                margin-top: -16px;
                margin-left: -16px;
                animation: breathe 2s ease-in-out infinite;
                -webkit-animation: breathe 2s ease-in-out infinite;
            }
        }
    }

    @keyframes breathe {
        0% { opacity: .2 }
        50% { opacity: 1 }
        100% { opacity: .2 }
    }
    @-webkit-keyframes breathe {
        0% { opacity: .2 }
        50% { opacity: 1 }
        100% { opacity: .2 }
    }
</style>
